/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IKannaRoleProvier,
  IKannaRoleProvierInterface,
} from "../../../contracts/Roles/IKannaRoleProvier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "hasRole",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IKannaRoleProvier__factory {
  static readonly abi = _abi;
  static createInterface(): IKannaRoleProvierInterface {
    return new utils.Interface(_abi) as IKannaRoleProvierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKannaRoleProvier {
    return new Contract(address, _abi, signerOrProvider) as IKannaRoleProvier;
  }
}
