/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IKannaRoleProvier__factory } from "./IKannaRoleProvier__factory";
export { KannaRoles__factory } from "./KannaRoles__factory";
