/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IKannaRoleProvier } from "./IKannaRoleProvier";
export type { KannaRoles } from "./KannaRoles";
