/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  KnnHolderBadgeChecker,
  KnnHolderBadgeCheckerInterface,
} from "../../contracts/KnnHolderBadgeChecker";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_knnToken",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isAccumulative",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a060405234801561001057600080fd5b5060405161037c38038061037c83398101604081905261002f9161009a565b6001600160a01b0381166100895760405162461bcd60e51b815260206004820152601560248201527f496e76616c696420746f6b656e20616464726573730000000000000000000000604482015260640160405180910390fd5b6001600160a01b03166080526100ca565b6000602082840312156100ac57600080fd5b81516001600160a01b03811681146100c357600080fd5b9392505050565b6080516102976100e5600039600061012201526102976000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806301ffc9a7146100465780638f6d3c0b146100b05780639e5576e7146100b7575b600080fd5b61009b6100543660046101a6565b7fffffffff00000000000000000000000000000000000000000000000000000000167f11384aec000000000000000000000000000000000000000000000000000000001490565b60405190151581526020015b60405180910390f35b600061009b565b6100ca6100c53660046101ef565b6100d8565b6040519081526020016100a7565b6040517f70a0823100000000000000000000000000000000000000000000000000000000815273ffffffffffffffffffffffffffffffffffffffff838116600483015260009182917f000000000000000000000000000000000000000000000000000000000000000016906370a0823190602401602060405180830381865afa158015610169573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061018d9190610248565b1161019957600061019c565b60015b60ff169392505050565b6000602082840312156101b857600080fd5b81357fffffffff00000000000000000000000000000000000000000000000000000000811681146101e857600080fd5b9392505050565b6000806040838503121561020257600080fd5b823573ffffffffffffffffffffffffffffffffffffffff8116811461022657600080fd5b9150602083013561ffff8116811461023d57600080fd5b809150509250929050565b60006020828403121561025a57600080fd5b505191905056fea26469706673582212208efa443d551a0585780a4afb87bf9351a12b7c8ee09d0f37f6cac74ea86b429364736f6c63430008110033";

type KnnHolderBadgeCheckerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: KnnHolderBadgeCheckerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class KnnHolderBadgeChecker__factory extends ContractFactory {
  constructor(...args: KnnHolderBadgeCheckerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _knnToken: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<KnnHolderBadgeChecker> {
    return super.deploy(
      _knnToken,
      overrides || {}
    ) as Promise<KnnHolderBadgeChecker>;
  }
  override getDeployTransaction(
    _knnToken: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_knnToken, overrides || {});
  }
  override attach(address: string): KnnHolderBadgeChecker {
    return super.attach(address) as KnnHolderBadgeChecker;
  }
  override connect(signer: Signer): KnnHolderBadgeChecker__factory {
    return super.connect(signer) as KnnHolderBadgeChecker__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): KnnHolderBadgeCheckerInterface {
    return new utils.Interface(_abi) as KnnHolderBadgeCheckerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): KnnHolderBadgeChecker {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as KnnHolderBadgeChecker;
  }
}
