/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FxERC20ChildTunnel__factory } from "./FxERC20ChildTunnel__factory";
export { IDynamicBadgeChecker__factory } from "./IDynamicBadgeChecker__factory";
